// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uybiahzqcrmjpgzhauji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5YmlhaHpxY3JtanBnemhhdWppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3OTQyNTMsImV4cCI6MjA4ODM3MDI1M30.7WpEaj6KMwjTXJsH-o95be73gsKYNDIyriki_u80FIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});